### ISSUE TITLE
AWS Plugin Quality of Life Improvements

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#12648]
These changes are breaking, so they should be bulked into a single major release.

### Tasks to be considered:
- [ ] Refactor SNS resolver to better follow the APIs... https://github.com/cloudquery/cloudquery/issues/12068#issuecomment-1628412100
- [x] Investigate switching from `GetAccountAuthorizationDetails` to `ListPolicies` for `aws_iam_policies` as `GetAuthorizationDetails` returns a lot of information that we do not need/use

### Tasks that are possibly out of scope:
- [ ] Refactor to better handle regions #10893 (we are not going to handle it in v23)
- [ ] https://github.com/cloudquery/cloudquery/issues/15391
- [ ] https://github.com/cloudquery/cloudquery/issues/12968

```[tasklist]
### Tasks
- [ ] https://github.com/cloudquery/cloudquery/pull/15377
- [ ] https://github.com/cloudquery/cloudquery/pull/15378
- [ ] https://github.com/cloudquery/cloudquery/pull/15380
- [ ] https://github.com/cloudquery/cloudquery/issues/15381
- [ ] https://github.com/cloudquery/cloudquery/issues/3466
- [ ] https://github.com/cloudquery/cloudquery/issues/15372
- [ ] https://github.com/cloudquery/cloudquery/issues/12974
- [ ] https://github.com/cloudquery/cloudquery/pull/15370
- [ ] https://github.com/cloudquery/cloudquery/pull/15398
- [ ] https://github.com/cloudquery/cloudquery/issues/15404
- [ ] https://github.com/cloudquery/cloudquery/issues/15411
- [ ] https://github.com/cloudquery/cloudquery/issues/15408
- [ ] https://github.com/cloudquery/cloudquery/pull/15423
- [ ] https://github.com/cloudquery/cloudquery/issues/12769
- [ ] https://github.com/cloudquery/cloudquery/issues/11029
- [ ] https://github.com/cloudquery/cloudquery/issues/15387
- [ ] https://github.com/cloudquery/cloudquery/issues/12646
```

**Comment by jsonpr** [comment]
https://github.com/cloudquery/cloudquery/issues/12968 as well.
