### ISSUE TITLE
feat: Add S3 Event Notifications and S3 Object Lock to AWS source plugin

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#13056]
### Describe the resource

S3 Event Notifications and S3 Object Lock Information

### Use Case

S3 Event Notifications and S3 Object Lock Information

### Link to API documentation

https://docs.aws.amazon.com/AmazonS3/latest/userguide/EventNotifications.html

### Pull request (optional)

- [ ] I can submit a pull request
```[tasklist]
### Tasks
- [ ] https://github.com/cloudquery/cloudquery/issues/13605
- [ ] https://github.com/cloudquery/cloudquery/issues/13606
```
