### ISSUE TITLE
feat: Add load balancer to gcp source plugin

### ISSUE THREAD

**Issue by songant** [cloudquery/cloudquery#13443]
### Describe the resource

Whether to synchronize load balancing related resources on gcp

### Use Case

I want to obtain data related to load balancing, in order to calculate the bill

### Link to API documentation

https://cloud.google.com/load-balancing/docs/load-balancing-overview

### Additional Context

```[tasklist]
### Tasks
- [x] Addresses- `gcp_compute_addresses`
- [x] Backend buckets
- [x] Backend services - `gcp_compute_backend_services`
- [x] Forwarding rules - `gcp_compute_forwarding_rules`
- [x] Health checks -  not yet supported
- [x] Instance groups - `gcp_compute_instance_groups`
- [x] NEGs
- [x] SSL certificates - `gcp_compute_ssl_certificates`
- [x] SSL policies- `gcp_compute_ssl_policies`
- [x] Target instances
- [x] Target pools
- [x] Target proxies- `gcp_compute_target_http_proxies` and `gcp_compute_target_ssl_proxies`
- [x] URL maps- `gcp_compute_url_maps`
```

**Comment by bbernays** [comment]
In GCP there isn't a single resource called a `load balancer` the [GCP Load Balancing](https://cloud.google.com/load-balancing/docs/load-balancing-overview) is comprised of many resources including:
Addresses- `gcp_compute_addresses`
Backend buckets -  not yet supported
Backend services - `gcp_compute_backend_services`
Forwarding rules - `gcp_compute_forwarding_rules`
Health checks -  not yet supported
Instance groups - `gcp_compute_instance_groups`
NEGs - Not supported
SSL certificates - `gcp_compute_ssl_certificates`
SSL policies- `gcp_compute_ssl_policies`
Target instances - not yet supported
Target pools - not yet supported
Target proxies- `gcp_compute_target_http_proxies and `gcp_compute_target_ssl_proxies`
URL maps- `gcp_compute_url_maps`

**Comment by AviKozokin** [comment]
Hi @bbernays 
It looks like there is a resource that isn't included: `gcp_compute_target_https_proxies`
(`gcp_compute_target_http_proxies` are for http only proxies, whereas `gcp_compute_target_ssl_proxies` are for Network Load Balancing)
https://cloud.google.com/compute/docs/reference/rest/v1/targetSslProxies
https://cloud.google.com/compute/docs/reference/rest/v1/targetHttpsProxies
https://cloud.google.com/compute/docs/reference/rest/v1/targetHttpProxies
