### ISSUE TITLE
feat: Move all plugins spec to support JSONSchema

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#13877]
We don't need to remove prior validation but rather just add the jsonschema validation on top (later we can maybe remove the go validation).  This is blocked by https://github.com/cloudquery/plugin-sdk/pull/1214

This is needed for our cloud version first and foremost and also to improve user experience in our registry.

```[tasklist]
### Tasks
- [ ] https://github.com/cloudquery/cloudquery/issues/13998
- [ ] https://github.com/cloudquery/cloudquery/issues/14615
- [ ] https://github.com/cloudquery/cloudquery/issues/14658
- [ ] https://github.com/cloudquery/cloudquery/issues/14654
- [ ] https://github.com/cloudquery/cloudquery/issues/14655
- [ ] https://github.com/cloudquery/cloudquery/issues/16503
- [ ] https://github.com/cloudquery/cloudquery/issues/16504
- [ ] https://github.com/cloudquery/cloudquery/issues/16505
```

**Comment by candiduslynx** [comment]
I'm looking into the JSON schema for our plugin spec & I’m wondering if a possibility to generate the schema instead of manually updating it would be better.

Basically, I’m looking into https://github.com/invopop/jsonschema & tags that should help us markup the schema.

Then, I’m going to add a simple pkg that we’ll be able to `install` (maybe add it to https://github.com/cloudquery/codegen, not sure) & run generation for the spec updates afterwards.

WDYT?

**Comment by yevgenypats** [comment]
> I'm looking into the JSON schema for our plugin spec & I’m wondering if a possibility to generate the schema instead of manually updating it would be better.
> 
> Basically, I’m looking into https://github.com/invopop/jsonschema & tags that should help us markup the schema.
> 
> Then, I’m going to add a simple pkg that we’ll be able to `install` (maybe add it to https://github.com/cloudquery/codegen, not sure) & run generation for the spec updates afterwards.
> 
> WDYT?

I think it must be schema first to make sure consistency and cross language - described here - https://cloudqueryio.slack.com/archives/C021N25N0TC/p1695120946855359?thread_ts=1695119854.215219&cid=C021N25N0TC

**Comment by candiduslynx** [comment]
I won't be making a generator for now because of the bugs discovered:
* https://github.com/invopop/jsonschema/issues/98
* https://github.com/invopop/jsonschema/issues/99

However, the https://github.com/invopop/jsonschema makes it easy to write a small gen code like so:
```go
package jsonschema

import (
	"encoding/json"
	"reflect"

	"github.com/invopop/jsonschema"
)

func Generate(a any) ([]byte, error) {
	sc := (&jsonschema.Reflector{RequiredFromJSONSchemaTags: true}).ReflectFromType(reflect.TypeOf(a))
	return json.MarshalIndent(sc, "", "  ")
}
```

**Comment by candiduslynx** [comment]
UPD: created https://github.com/invopop/jsonschema/pull/100 to unblock codegen
