### ISSUE TITLE
Add JSON schema to source plugins

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#13998]
```[tasklist]
### Tasks
- [ ] https://github.com/cloudquery/cloudquery/issues/16450
- [ ] https://github.com/cloudquery/cloudquery/issues/16334
- [ ] https://github.com/cloudquery/cloudquery/issues/14027
- [ ] https://github.com/cloudquery/cloudquery/issues/16425
- [ ] https://github.com/cloudquery/cloudquery/issues/14553
- [ ] https://github.com/cloudquery/cloudquery/issues/16426
- [ ] https://github.com/cloudquery/cloudquery/issues/16567
- [ ] https://github.com/cloudquery/cloudquery/issues/16374
- [ ] https://github.com/cloudquery/cloudquery/issues/16335
- [ ] https://github.com/cloudquery/cloudquery/issues/16336
- [ ] https://github.com/cloudquery/cloudquery/issues/16331
- [ ] https://github.com/cloudquery/cloudquery/issues/16332
- [ ] https://github.com/cloudquery/cloudquery/issues/16333
- [ ] https://github.com/cloudquery/cloudquery/issues/16568
- [ ] https://github.com/cloudquery/cloudquery/issues/16359
- [ ] https://github.com/cloudquery/cloudquery/issues/16569
- [ ] https://github.com/cloudquery/cloudquery/issues/13999
- [ ] https://github.com/cloudquery/cloudquery/issues/16360
- [ ] https://github.com/cloudquery/cloudquery/issues/16361
- [ ] https://github.com/cloudquery/cloudquery/issues/16570
- [ ] https://github.com/cloudquery/cloudquery/issues/14451
- [ ] https://github.com/cloudquery/cloudquery/issues/16375
- [ ] https://github.com/cloudquery/cloudquery/issues/16571
- [ ] https://github.com/cloudquery/cloudquery/issues/16376
- [ ] https://github.com/cloudquery/cloudquery/issues/16427
- [ ] https://github.com/cloudquery/cloudquery/issues/16451
- [ ] https://github.com/cloudquery/cloudquery/issues/14450
- [ ] https://github.com/cloudquery/cloudquery/issues/16577
- [ ] https://github.com/cloudquery/cloudquery/issues/16452
- [ ] https://github.com/cloudquery/cloudquery/issues/16576
- [ ] https://github.com/cloudquery/cloudquery/issues/16377
- [ ] https://github.com/cloudquery/cloudquery/issues/16575
- [ ] https://github.com/cloudquery/cloudquery/issues/16453
- [ ] https://github.com/cloudquery/cloudquery/issues/14000
- [ ] https://github.com/cloudquery/cloudquery/issues/16454
- [ ] https://github.com/cloudquery/cloudquery/issues/16455
- [ ] https://github.com/cloudquery/cloudquery/issues/16574
- [ ] https://github.com/cloudquery/cloudquery/issues/16378
- [ ] https://github.com/cloudquery/cloudquery/issues/16573
- [ ] https://github.com/cloudquery/cloudquery/issues/16456
- [ ] https://github.com/cloudquery/cloudquery/issues/16347
- [ ] https://github.com/cloudquery/cloudquery/issues/16572
- [ ] https://github.com/cloudquery/cloudquery/issues/16457
- [ ] https://github.com/cloudquery/cloudquery/issues/16458
- [ ] https://github.com/cloudquery/cloudquery/issues/16348
- [ ] https://github.com/cloudquery/cloudquery/issues/16581
- [ ] https://github.com/cloudquery/cloudquery/issues/16459
- [ ] https://github.com/cloudquery/cloudquery/issues/16353
- [ ] https://github.com/cloudquery/cloudquery/issues/16460
- [ ] https://github.com/cloudquery/cloudquery-issues/issues/1295
- [ ] https://github.com/cloudquery/cloudquery/issues/16367
```
