### ISSUE TITLE
CQ<>Config Resource Support Compatibility

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#1411]
Goal is to cover all resources that AWS config does so we can provide the same level or coverage. Below are the resources that we are missing at this time

- [x] cloudquery/cq-provider-aws#615
- [x] cloudquery/cq-provider-aws#618
- [x] cloudquery/cq-provider-aws#628
- [x] cloudquery/cq-provider-aws#627
- [x] cloudquery/cq-provider-aws#658
- [x] cloudquery/cq-provider-aws#620
- [x] cloudquery/cq-provider-aws#626
- [x] cloudquery/cloudquery#1410
- [x] cloudquery/cq-provider-aws#623
- [x] cloudquery/cloudquery#1409
- [x] cloudquery/cq-provider-aws#625
- [x] cloudquery/cq-provider-aws#621
- [x] cloudquery/cq-provider-aws#619
- [x] cloudquery/cq-provider-aws#617
- [x] cloudquery/cq-provider-aws#616

**Comment by yevgenypats** [comment]
Closing as seems everything is done here.
