### ISSUE TITLE
Add JSON schema to destination plugins

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#14615]
```[tasklist]
### Tasks
- [ ] https://github.com/cloudquery/cloudquery/issues/16405
- [ ] https://github.com/cloudquery/cloudquery/issues/16447
- [ ] https://github.com/cloudquery/cloudquery/issues/14616
- [ ] https://github.com/cloudquery/cloudquery/issues/16349
- [ ] https://github.com/cloudquery/cloudquery/issues/16448
- [ ] https://github.com/cloudquery/cloudquery/issues/14619
- [ ] https://github.com/cloudquery/cloudquery/issues/16449
- [ ] https://github.com/cloudquery/cloudquery/issues/16407
- [ ] https://github.com/cloudquery/cloudquery/issues/16350
- [ ] https://github.com/cloudquery/cloudquery/issues/16406
- [ ] https://github.com/cloudquery/cloudquery/issues/16436
- [ ] https://github.com/cloudquery/cloudquery/issues/16392
- [ ] https://github.com/cloudquery/cloudquery/issues/16434
- [ ] https://github.com/cloudquery/cloudquery/issues/16435
- [ ] https://github.com/cloudquery/cloudquery/issues/16351
- [ ] https://github.com/cloudquery/cloudquery/issues/14617
- [ ] https://github.com/cloudquery/cloudquery/issues/14618
- [ ] https://github.com/cloudquery/cloudquery/issues/16390
- [ ] https://github.com/cloudquery/cloudquery/issues/16391
- [ ] https://github.com/cloudquery/cloudquery/issues/16352
```
