### ISSUE TITLE
Several AWS resources have duplicates

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#6837]
### Describe the Bug
Several AWS resources have duplicate primary keys:
* [ ] `aws_backup_global_settings` (#6844)
* [x] `aws_docdb_engine_versions` (#6846)
* [x] `aws_glue_datacatalog_encryption_settings` (#6845)
* [x] `aws_lambda_runtimes` (#6849)
* [x] `aws_ram_resource_types` (#6850)
* [x] `aws_rds_engine_versions` (#6851)
* [x] `aws_wafv2_managed_rule_groups` (#6843)

### Expected Behavior
Different resources have different PK.

### CloudQuery Version
`cloudquery version 2.0.26`

### AWS plugin version
`11.0.1`
