### ISSUE TITLE
Primary key violations

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#7173]
## Action items

- [x] Check for primary keys violations in destinations
  - [x] Check in a single batch (https://github.com/cloudquery/plugin-sdk/issues/627)
- [x] Fix primary key violations found:
  - [x] AWS (#7181)
  - [x] Azure (#7183)

## Issue description

Some resources have duplicate primary keys.

## User impact

The issue was discovered during syncs to [Microsoft SQL Server destination](https://www.cloudquery.io/docs/plugins/destinations/mssql/overview). Other destination plugins don't highlight the issue at the moment. Instead, the data written ends up being a single record instead of multiple ones (`overwrite` and `overwrite-delete-stale` modes).

### Observed issues

- #6837
- #6984

### Related

- #7175
