### ISSUE TITLE
feat(repo-configuration): Move our issues templates to issue forms

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#8946]
Specifically for this repository, but also others.
This repository doesn't use GitHub issue forms, hence new issues lack structure.
Also in other repositories we use issue forms, but those are inherited from https://github.com/cloudquery/.github/tree/main/.github/ISSUE_TEMPLATE which are not suitable for all repositories.
For example the SDK should not have a new resource template, see https://github.com/cloudquery/plugin-sdk/issues/new/choose (same for other repos, see https://github.com/cloudquery/helm-charts/issues/new/choose, https://github.com/cloudquery/setup-cloudquery/issues/new/choose, etc.)

### TODO

- [x] Remove generic issue templates from `.github` as those are not relevant https://github.com/cloudquery/.github/pull/390
- [x] Create dedicated issue templates for `cloudquery/cloudquery` repo https://github.com/cloudquery/cloudquery/pull/9014
- [x] Create dedicated issue templates for `cloudquery/plugin-sdk` repo https://github.com/cloudquery/plugin-sdk/pull/731
- [x] Create dedicated issue templates for `cloudquery/helm-charts` repo https://github.com/cloudquery/helm-charts/pull/283
- [x] Create dedicated issue templates for `cloudquery/setup-cloudquery` repo https://github.com/cloudquery/setup-cloudquery/pull/234
- [x] Create dedicated issue templates for `cloudquery/terraform-aws-cloudquery` repo https://github.com/cloudquery/terraform-aws-cloudquery/pull/305
- [x] Create dedicated issue templates for `cloudquery/filetypes` repo https://github.com/cloudquery/filetypes/pull/93

**Comment by erezrokah** [comment]
This can be closed as all PRs were merged
